import authService from "./authService";

const API_BASE_URL = "https://enviguide.nextechltd.in";

// Master Data Setup entities - use /api/master-data-setup/...
export type MasterDataEntity =
  | "material-composition-metal"
  | "country-iso-two"
  | "country-iso-three"
  | "scope-two-method"
  | "method-type"
  | "transport-modes"
  | "transport-routes"
  | "packaging-level"
  | "waste-treatment"
  | "life-cycle-stage"
  | "life-cycle-boundary"
  | "energy-source"
  | "energy-type"
  | "energy-unit"
  | "water-source"
  | "water-treatment"
  | "water-unit"
  | "discharge-destination"
  | "allocation-method"
  | "product-unit"
  | "gaseous-fuel-unit"
  | "liquid-fuel-unit"
  | "solid-fuel-unit"
  | "ef-unit"
  | "fuel-type"
  | "sub-fuel-type"
  | "reporting-standard"
  | "certificate-type"
  | "verification-status"
  | "credit-method"
  | "supplier-tier"
  | "refrigerent-type"
  | "time-zone"
  | "process-specific-energy"
  | "vehicle-type";

// Master Data items use simple {name} schema for add (code is auto-generated by backend)
export interface MasterDataItem {
  id?: string;
  code?: string; // Auto-generated by backend, shown in list
  name: string;
  // For sub-fuel-type entity
  ft_id?: string; // Foreign key to fuel-type
  fuel_type_name?: string; // Display name of related fuel type
  // For energy-type entity
  es_id?: string; // Foreign key to energy-source
  energy_source_name?: string; // Display name of related energy source
}

// ID field mapping for different entities (backend uses different ID field names)
const idFieldMapping: Record<string, string> = {
  "material-composition-metal": "mcm_id",
  "country-iso-two": "citw_id",
  "country-iso-three": "cith_id",
  "scope-two-method": "stm_id",
  "method-type": "mt_id",
  "transport-modes": "tm_id",
  "transport-routes": "tr_id",
  "packaging-level": "pl_id",
  "waste-treatment": "wt_id",
  "life-cycle-stage": "lcs_id",
  "life-cycle-boundary": "lcb_id",
  "energy-source": "es_id",
  "energy-type": "et_id",
  "energy-unit": "eu_id",
  "water-source": "ws_id",
  "water-treatment": "wat_id",
  "water-unit": "wu_id",
  "discharge-destination": "dd_id",
  "allocation-method": "am_id",
  "product-unit": "pu_id",
  "gaseous-fuel-unit": "gfu_id",
  "liquid-fuel-unit": "lfu_id",
  "solid-fuel-unit": "sfu_id",
  "ef-unit": "efu_id",
  "fuel-type": "ft_id",
  "sub-fuel-type": "sft_id",
  "reporting-standard": "rs_id",
  "certificate-type": "ct_id",
  "verification-status": "vs_id",
  "credit-method": "cm_id",
  "supplier-tier": "spt_id",
  "refrigerent-type": "rt_id",
  "time-zone": "tz_id",
  "process-specific-energy": "pse_id",
  "vehicle-type": "vt_id",
};

function getAuthHeaders() {
  const token = authService.getToken();
  return {
    "Content-Type": "application/json",
    Authorization: token || "",
  } as Record<string, string>;
}

function endpoint(
  entity: MasterDataEntity,
  action: "list/search" | "add" | "update" | "delete" | "bulk/add" | "drop-down-list"
) {
  return `${API_BASE_URL}/api/master-data-setup/${entity}/${action}`;
}

// Get the ID field name for an entity
function getIdField(entity: MasterDataEntity): string {
  return idFieldMapping[entity] || "id";
}

// Extract ID from an item based on entity type
function extractId(entity: MasterDataEntity, item: any): string {
  const idField = getIdField(entity);
  return item[idField]?.toString() || item.id?.toString() || item._id?.toString() || "";
}

export async function listMasterData(
  entity: MasterDataEntity,
  params?: { searchValue?: string }
): Promise<MasterDataItem[]> {
  const url = new URL(endpoint(entity, "list/search"));
  if (params?.searchValue)
    url.searchParams.set("searchValue", params.searchValue);
  const res = await fetch(url.toString(), {
    method: "GET",
    headers: getAuthHeaders(),
  });
  const data = await res.json();
  // Expected: { status, message, code, data: { totalCount, list: [] } }
  const normalizeItem = (item: any): MasterDataItem => {
    const normalized: MasterDataItem = {
      id: extractId(entity, item),
      code: item.code || "",
      name: item.name || "",
    };
    // Include additional fields for sub-fuel-type
    if (entity === "sub-fuel-type") {
      normalized.ft_id = item.ft_id || "";
      normalized.fuel_type_name = item.fuel_type_name || "";
    }
    // Include additional fields for energy-type
    if (entity === "energy-type") {
      normalized.es_id = item.es_id || "";
      normalized.energy_source_name = item.energy_source_name || "";
    }
    return normalized;
  };

  if (Array.isArray((data as any)?.data?.list)) {
    return ((data as any).data.list as any[]).map(normalizeItem);
  }
  // Fallbacks
  if (Array.isArray(data)) return (data as any[]).map(normalizeItem);
  if (Array.isArray((data as any)?.data))
    return ((data as any).data as any[]).map(normalizeItem);
  if (Array.isArray((data as any)?.items))
    return ((data as any).items as any[]).map(normalizeItem);
  return [];
}

export async function addMasterData(
  entity: MasterDataEntity,
  item: MasterDataItem
): Promise<{ success: boolean; message?: string }> {
  try {
    // Build payload based on entity type
    let payload: Record<string, any> = { name: item.name };

    // sub-fuel-type requires ft_id
    if (entity === "sub-fuel-type" && item.ft_id) {
      payload.ft_id = item.ft_id;
    }
    // energy-type requires es_id
    if (entity === "energy-type" && item.es_id) {
      payload.es_id = item.es_id;
    }

    const res = await fetch(endpoint(entity, "add"), {
      method: "POST",
      headers: getAuthHeaders(),
      body: JSON.stringify(payload),
    });
    const data = await res.json();
    const success = !!(data?.success ?? data?.status);
    return {
      success,
      message: data?.message,
    };
  } catch (error) {
    return {
      success: false,
      message: "An error occurred while adding item",
    };
  }
}

export async function updateMasterData(
  entity: MasterDataEntity,
  item: MasterDataItem & { id: string }
): Promise<{ success: boolean; message?: string }> {
  try {
    const idField = getIdField(entity);
    const updatePayload: Record<string, any> = {
      [idField]: item.id,
      name: item.name,
    };

    // sub-fuel-type requires ft_id in update
    if (entity === "sub-fuel-type" && item.ft_id) {
      updatePayload.ft_id = item.ft_id;
    }
    // energy-type requires es_id in update
    if (entity === "energy-type" && item.es_id) {
      updatePayload.es_id = item.es_id;
    }

    const res = await fetch(endpoint(entity, "update"), {
      method: "POST",
      headers: getAuthHeaders(),
      body: JSON.stringify([updatePayload]),
    });
    const data = await res.json();
    const success = !!(data?.success ?? data?.status);
    return {
      success,
      message: data?.message,
    };
  } catch (error) {
    return {
      success: false,
      message: "An error occurred while updating item",
    };
  }
}

export async function deleteMasterData(
  entity: MasterDataEntity,
  id: string
): Promise<{ success: boolean; message?: string }> {
  try {
    const idField = getIdField(entity);
    const res = await fetch(endpoint(entity, "delete"), {
      method: "POST",
      headers: getAuthHeaders(),
      body: JSON.stringify({ [idField]: id }),
    });
    const data = await res.json();
    const success = !!(data?.success ?? data?.status);
    return {
      success,
      message: data?.message,
    };
  } catch (error) {
    return {
      success: false,
      message: "An error occurred while deleting item",
    };
  }
}

export async function bulkAddMasterData(
  entity: MasterDataEntity,
  items: MasterDataItem[]
): Promise<{ success: boolean; message: string; addedCount?: number }> {
  try {
    // Build payload based on entity type
    const payload = items.map((item) => {
      // sub-fuel-type bulk add uses fuel_type_name instead of ft_id
      if (entity === "sub-fuel-type") {
        return {
          fuel_type_name: item.fuel_type_name || "",
          name: item.name,
        };
      }
      // energy-type bulk add uses energy_source_name instead of es_id
      if (entity === "energy-type") {
        return {
          energy_source_name: item.energy_source_name || "",
          name: item.name,
        };
      }
      return { name: item.name };
    });

    const res = await fetch(endpoint(entity, "bulk/add"), {
      method: "POST",
      headers: getAuthHeaders(),
      body: JSON.stringify(payload),
    });
    const data = await res.json();
    if (data?.success || data?.status) {
      return {
        success: true,
        message: data?.message || "Bulk import successful",
        addedCount: data?.data?.addedCount || items.length,
      };
    }
    return {
      success: false,
      message: data?.message || "Bulk import failed",
    };
  } catch (error) {
    return {
      success: false,
      message: "An error occurred during bulk import",
    };
  }
}

export async function getDropdownList(
  entity: MasterDataEntity
): Promise<{ id: string; name: string }[]> {
  try {
    const res = await fetch(endpoint(entity, "drop-down-list"), {
      method: "GET",
      headers: getAuthHeaders(),
    });
    const data = await res.json();
    if (Array.isArray(data?.data)) {
      return (data.data as any[]).map((item) => ({
        id: extractId(entity, item),
        name: item.name || "",
      }));
    }
    return [];
  } catch (error) {
    return [];
  }
}

// Get fuel types from data-setup API (for sub-fuel-type dropdown)
export async function getFuelTypeDropdown(): Promise<{ id: string; name: string }[]> {
  try {
    const res = await fetch(`${API_BASE_URL}/api/data-setup/fuel-type/list`, {
      method: "GET",
      headers: getAuthHeaders(),
    });
    const data = await res.json();
    if (Array.isArray(data?.data)) {
      return (data.data as any[]).map((item) => ({
        id: item.id || "",
        name: item.name || "",
      }));
    }
    return [];
  } catch (error) {
    return [];
  }
}

// Get energy sources from master-data-setup API (for energy-type dropdown)
export async function getEnergySourceDropdown(): Promise<{ id: string; name: string }[]> {
  try {
    const res = await fetch(endpoint("energy-source", "drop-down-list"), {
      method: "GET",
      headers: getAuthHeaders(),
    });
    const data = await res.json();
    if (Array.isArray(data?.data)) {
      return (data.data as any[]).map((item) => ({
        id: item.es_id || item.id || "",
        name: item.name || "",
      }));
    }
    return [];
  } catch (error) {
    return [];
  }
}
